@Marquee_HostAddress = http://localhost:5055

### Create a new Media item
POST http://localhost:5055/api/media
Content-Type: application/json

{
  
}

### Get all Media items to verify it saved
GET http://localhost:5055/api/media